//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guardhouse
    {
        public int id { get; set; }
        public string condominio { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string responsable { get; set; }
        public string emailresponsable { get; set; }
        public string telefonoresponsable { get; set; }
        public string estatus { get; set; }
        public string clave { get; set; }
        public string condominiositio { get; set; }
    }
}
