//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modulo
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string texto { get; set; }
        public string intro { get; set; }
        public string descripcion { get; set; }
        public string icono { get; set; }
        public Nullable<int> premodulo { get; set; }
        public string perfiles { get; set; }
        public Nullable<int> agrupador { get; set; }
        public string estatus { get; set; }
    }
}
