//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personavehiculo
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int idpersona { get; set; }
        public int idvehiculo { get; set; }
        public string estatus { get; set; }
        public Nullable<bool> listanegra { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
