//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idPuerta { get; set; }
        public int noTurno { get; set; }
        public string nombre { get; set; }
        public string estatus { get; set; }
        public string horaInicio { get; set; }
        public string horaFin { get; set; }
        public int horas { get; set; }
    
        public virtual puerta puerta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
