//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariobitacora
    {
        public int id { get; set; }
        public int idusuario { get; set; }
        public string email { get; set; }
        public string accion { get; set; }
        public System.DateTime fecha { get; set; }
        public string hora { get; set; }
        public string infoguardia { get; set; }
        public string detalle { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
