//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public int id { get; set; }
        public string placa { get; set; }
        public string marca { get; set; }
        public string submarca { get; set; }
        public string color { get; set; }
        public int idvisitante { get; set; }
    
        public virtual visitante visitante { get; set; }
    }
}
